#!/bin/sh

if [ "`id -u`" != "0" ]; then
  echo "sorry, this must be done as root." 1>&2
  exit 1
fi

if [ -z "${DESTDIR}" ]; then
  echo "DESTDIR not set" 1>&2
  exit 1
fi

files=""
files="${files} bin/cat"
files="${files} bin/chmod"
files="${files} bin/cp"
files="${files} bin/csh"
files="${files} bin/echo"
files="${files} bin/expr"
files="${files} bin/hostname"
files="${files} bin/link"
files="${files} bin/ln"
files="${files} bin/ls"
files="${files} bin/mkdir"
files="${files} bin/mv"
files="${files} bin/ps"
files="${files} bin/realpath"
files="${files} bin/rm"
files="${files} bin/rmdir"
files="${files} bin/sh"
files="${files} bin/sleep"
files="${files} bin/unlink"
files="${files} sbin/md5"
files="${files} sbin/sha1"
files="${files} sbin/sha256"
files="${files} sbin/sha512"
files="${files} usr/bin/ar"
files="${files} usr/bin/as"
files="${files} usr/bin/awk"
files="${files} usr/bin/basename"
files="${files} usr/bin/bsdtar"
files="${files} usr/bin/bunzip2"
files="${files} usr/bin/byacc"
files="${files} usr/bin/bzip2"
files="${files} usr/bin/c++"
files="${files} usr/bin/chgrp"
files="${files} usr/bin/clang"
files="${files} usr/bin/clang-cpp"
files="${files} usr/bin/clang++"
files="${files} usr/bin/cmp"
files="${files} usr/bin/diff"
files="${files} usr/bin/dirname"
files="${files} usr/bin/env"
files="${files} usr/bin/fetch"
files="${files} usr/bin/find"
files="${files} usr/bin/flex"
files="${files} usr/bin/flex++"
files="${files} usr/bin/gunzip"
files="${files} usr/bin/gzcat"
files="${files} usr/bin/gzip"
files="${files} usr/bin/id"
files="${files} usr/bin/install"
files="${files} usr/bin/ld"
files="${files} usr/bin/ld.bfd"
files="${files} usr/bin/ld.lld"
files="${files} usr/bin/lex"
files="${files} usr/bin/lex++"
files="${files} usr/bin/limits"
files="${files} usr/bin/llvm-objdump"
files="${files} usr/bin/lorder"
files="${files} usr/bin/lzma"
# files="${files} usr/bin/make"    # MACHINE and MACHINE_ARCH are not set to cross-target values
files="${files} usr/bin/makewhatis"
files="${files} usr/bin/mandoc"
files="${files} usr/bin/mktemp"
files="${files} usr/bin/nawk"
files="${files} usr/bin/nm"
files="${files} usr/bin/objcopy"
files="${files} usr/bin/patch"
files="${files} usr/bin/ranlib"
files="${files} usr/bin/readelf"
files="${files} usr/bin/sed"
files="${files} usr/bin/size"
files="${files} usr/bin/sort"
files="${files} usr/bin/strings"
files="${files} usr/bin/strip"
files="${files} usr/bin/touch"
files="${files} usr/bin/tr"
files="${files} usr/bin/true"
files="${files} usr/bin/uniq"
files="${files} usr/bin/unlzma"
files="${files} usr/bin/unxz"
files="${files} usr/bin/unzip"
files="${files} usr/bin/xargs"
files="${files} usr/bin/xz"
files="${files} usr/bin/yacc"
files="${files} usr/sbin/chown"

for i in ${files}; do
  if [ -f "${DESTDIR}/nxb-bin/${i}" ]; then
    echo "linking ${i}"
    ln -f "${DESTDIR}/nxb-bin/${i}" "${DESTDIR}/${i}" || exit 1
  fi
done
